apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: gcr.io/qubernetes/nodejs:0.2
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
